### ISSUE TITLE
Could you plz share all github repository folders?

### ISSUE THREAD

**Issue by anks12297** [shangqing-liu/CCSD-benchmark-for-code-summarization#3]
Thank you for providing CCSD dataset. Can you please share all github repositories for all functions? Or How can I get/download/clone all repositories?

**Comment by shangqing-liu** [comment]
Hi, @anks12297 

Sorry for the late reply and thanks for your attention to our CCSD dataset, because of the maintenance of our server, the original repos from GitHub have already been missed. But I think you can parse the file_path provided in our all_functions.csv to get the original repo name, then you can use "git clone  xxx" to clone these projects by yourselves.

Sorry for the inconvenience.
